# File: .github/workflows/deploy.yml

name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This zips the entire 'order-service' directory (excluding node_modules)
      # which is the standard way to deploy Node.js apps to Elastic Beanstalk.
      - name: Generate Deployment Package
        run: |
          cd order-service
          zip -r ../deploy.zip . -x "node_modules/*"

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: order-management-system
          environment_name: OrderManagementSystem-env
          version_label: "v${{ github.run_number }}-${{ github.sha }}"
          region: "ap-south-1"
          deployment_package: deploy.zip
          use_existing_version_if_available: true
