# File: .github/workflows/deploy.yml

name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: ./order-service
        run: npm install

      - name: Generate Deployment Package
        run: |
          mkdir deploy
          cp -R order-service/src deploy/
          cp order-service/package.json deploy/
          cp order-service/package-lock.json deploy/
          cd deploy
          zip -r ../deploy.zip .

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: order-management-system
          environment_name: OrderManagementSystem-env
          
          # --- THIS IS THE UPDATED LINE ---
          # It now combines the run number with the unique Git commit ID (short version).
          # This ensures the version label is always unique.
          version_label: "v${{ github.run_number }}-${{ github.sha }}"
          
          region: "ap-south-1"
          deployment_package: deploy.zip
